FROM nginx:alpine

# Borrar config default
RUN rm /etc/nginx/conf.d/default.conf

# Copiar build del frontend
COPY frontend/dist/ /usr/share/nginx/html

# Copiar config personalizada
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
