FROM node:18

WORKDIR /app

COPY backend/package*.json ./
RUN npm install

COPY backend/ ./

COPY docker/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

EXPOSE 4000

CMD ["/wait-for-it.sh", "mysql:3306", "--", "node", "server.js"]
